AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda for IOT
Globals:
  Function:
    Timeout: 5
Resources:
  IAMAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IOTDeviceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - credentials.iot.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - execute-api:Invoke
            Resource:
              Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TestServiceAPI}/Prod/*/*
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
              Fn::GetAtt:
              - TestServiceFunction
              - Arn
  TestServiceAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: '''*'''
      Auth:
        DefaultAuthorizer: AWS_IAM
  TestServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://testsam773478/9134290707cf896f6ead62884a71b93f
      Handler: testservice
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId:
              Ref: TestServiceAPI
            Path: /hello
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
Outputs:
  TestServiceAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${TestServiceAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  TestServiceFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - TestServiceFunction
      - Arn
  TestServiceFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - TestServiceFunctionRole
      - Arn
  IAMAccessRole:
    Description: IAM Access role for IOT
    Value:
      Fn::GetAtt:
      - IAMAccessRole
      - Arn
