AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda for IOT

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  IAMAccessRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          Effect: "Allow"
          Principal: 
            Service: 
              - credentials.iot.amazonaws.com
          Action: "sts:AssumeRole"
  
      RoleName: IOTDeviceRole

  IAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:   
      Description: "Policy for IOT Devices"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: 
             - iam:GetRole
             - iam:PassRole
            Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:role/IOTDeviceRole
      

      

  TestServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: testservice/
      Handler: testservice
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TestServiceAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/testservice/"
  TestServiceFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt TestServiceFunction.Arn
  TestServiceFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TestServiceFunctionRole.Arn
  IAMAccessRole:
    Description: "IAM Access role for IOT"
    Value: !GetAtt IAMAccessRole.Arn